/-
Copyright (c) 2026 Yi-Jing Tseng. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yi-Jing Tseng
-/
module

public import Mathlib.MeasureTheory.SetAlgebra

/-!
# Monotone classes of sets

A monotone class is a family of sets closed under increasing countable unions and decreasing
countable intersections. This file defines the monotone class generated by a family of sets and
proves the monotone class theorem: the monotone class generated by an algebra of sets is the
σ-algebra generated by that algebra.

The theorem is presented both as an equality of generated families and as an induction principle
for measurable sets.
-/

@[expose] public section

open SigmaAlgebra Set

namespace MeasureTheory

variable {α : Type*} {𝒜 ℳ : Set (Set α)} {s t : Set α}

/-- A monotone class is a family of sets closed under increasing countable unions and decreasing
countable intersections. -/
structure IsMonotoneClass (ℳ : Set (Set α)) : Prop where
  /-- An increasing union of members of a monotone class belongs to the class. -/
  iUnion_mem : ∀ ⦃s : ℕ → Set α⦄, Monotone s → (∀ n, s n ∈ ℳ) → ⋃ n, s n ∈ ℳ
  /-- A decreasing intersection of members of a monotone class belongs to the class. -/
  iInter_mem : ∀ ⦃s : ℕ → Set α⦄, Antitone s → (∀ n, s n ∈ ℳ) → ⋂ n, s n ∈ ℳ

private inductive GenerateMonotoneClass (𝒜 : Set (Set α)) : Set α → Prop
  | basic (s : Set α) (hs : s ∈ 𝒜) : GenerateMonotoneClass 𝒜 s
  | iUnion (s : ℕ → Set α) (h_mono : Monotone s)
      (hs : ∀ n, GenerateMonotoneClass 𝒜 (s n)) : GenerateMonotoneClass 𝒜 (⋃ n, s n)
  | iInter (s : ℕ → Set α) (h_anti : Antitone s)
      (hs : ∀ n, GenerateMonotoneClass 𝒜 (s n)) : GenerateMonotoneClass 𝒜 (⋂ n, s n)

/-- The least monotone class containing a family of sets. -/
@[no_expose]
def generateMonotoneClass (𝒜 : Set (Set α)) : Set (Set α) :=
  {s | GenerateMonotoneClass 𝒜 s}

theorem self_subset_generateMonotoneClass : 𝒜 ⊆ generateMonotoneClass 𝒜 :=
  GenerateMonotoneClass.basic

theorem isMonotoneClass_generateMonotoneClass : IsMonotoneClass (generateMonotoneClass 𝒜) where
  iUnion_mem := GenerateMonotoneClass.iUnion
  iInter_mem := GenerateMonotoneClass.iInter

/-- An induction principle for membership in `generateMonotoneClass 𝒜`. -/
@[elab_as_elim]
theorem generateMonotoneClass_induction
    {motive : ∀ s, s ∈ generateMonotoneClass 𝒜 → Prop}
    (basic : ∀ s (hs : s ∈ 𝒜), motive s (self_subset_generateMonotoneClass hs))
    (iUnion : ∀ (s : ℕ → Set α) (h_mono : Monotone s)
      (hs : ∀ n, s n ∈ generateMonotoneClass 𝒜), (∀ n, motive (s n) (hs n)) →
        motive (⋃ n, s n) (isMonotoneClass_generateMonotoneClass.iUnion_mem h_mono hs))
    (iInter : ∀ (s : ℕ → Set α) (h_anti : Antitone s)
      (hs : ∀ n, s n ∈ generateMonotoneClass 𝒜), (∀ n, motive (s n) (hs n)) →
        motive (⋂ n, s n) (isMonotoneClass_generateMonotoneClass.iInter_mem h_anti hs))
    (hs : s ∈ generateMonotoneClass 𝒜) : motive s hs := by
  induction hs with
  | basic s hs => exact basic s hs
  | iUnion s h_mono hs ih => exact iUnion s h_mono hs ih
  | iInter s h_anti hs ih => exact iInter s h_anti hs ih

/-- A monotone class contains the monotone class generated by any subfamily. -/
theorem IsMonotoneClass.generateMonotoneClass_subset (hℳ : IsMonotoneClass ℳ) (h𝒜 : 𝒜 ⊆ ℳ) :
    generateMonotoneClass 𝒜 ⊆ ℳ := by
  intro s hs
  induction hs with
  | basic s hs => exact h𝒜 hs
  | iUnion s h_mono _ ih => exact hℳ.iUnion_mem h_mono ih
  | iInter s h_anti _ ih => exact hℳ.iInter_mem h_anti ih

/-- The operation of generating a monotone class is monotone. -/
theorem generateMonotoneClass_mono {ℬ : Set (Set α)} (h : 𝒜 ⊆ ℬ) :
    generateMonotoneClass 𝒜 ⊆ generateMonotoneClass ℬ :=
  isMonotoneClass_generateMonotoneClass.generateMonotoneClass_subset
    (h.trans self_subset_generateMonotoneClass)

theorem IsMonotoneClass.generateMonotoneClass_eq (h𝒜 : IsMonotoneClass 𝒜) :
    generateMonotoneClass 𝒜 = 𝒜 :=
  Set.Subset.antisymm (h𝒜.generateMonotoneClass_subset Subset.rfl)
    self_subset_generateMonotoneClass

end MeasureTheory

namespace SigmaAlgebra

open MeasureTheory

variable {α : Type*}

/-- The sets in a σ-algebra form a monotone class. -/
theorem isMonotoneClass (m : SigmaAlgebra α) : IsMonotoneClass (m : Set (Set α)) where
  iUnion_mem := fun _ _ hs ↦ m.iUnion_mem hs
  iInter_mem := fun _ _ hs ↦ m.iInter_mem hs

end SigmaAlgebra

namespace MeasureTheory

variable {α : Type*} {𝒜 ℳ : Set (Set α)} {s t : Set α}

/-- An algebra that is also a monotone class is closed under arbitrary countable unions. -/
theorem IsSetAlgebra.iUnion_mem_of_isMonotoneClass (h𝒜 : IsSetAlgebra 𝒜)
    (h_mono : IsMonotoneClass 𝒜) {s : ℕ → Set α} (hs : ∀ n, s n ∈ 𝒜) : ⋃ n, s n ∈ 𝒜 := by
  let cumulative : ℕ → Set α := fun n ↦ ⋃ i ∈ Finset.range (n + 1), s i
  have cumulative_mem (n : ℕ) : cumulative n ∈ 𝒜 :=
    h𝒜.biUnion_mem (Finset.range (n + 1)) fun i _ ↦ hs i
  have cumulative_mono : Monotone cumulative := by
    intro i j hij x hx
    simp only [cumulative, mem_iUnion, Finset.mem_range] at hx ⊢
    obtain ⟨k, hk, hx⟩ := hx
    exact ⟨k, hk.trans_le (Nat.add_le_add_right hij 1), hx⟩
  have cumulative_iUnion : ⋃ n, cumulative n = ⋃ n, s n := by
    ext x
    simp only [cumulative, mem_iUnion, Finset.mem_range]
    constructor
    · rintro ⟨n, i, -, hxi⟩
      exact ⟨i, hxi⟩
    · rintro ⟨i, hxi⟩
      exact ⟨i, i, Nat.lt_succ_self i, hxi⟩
  rw [← cumulative_iUnion]
  exact h_mono.iUnion_mem cumulative_mono cumulative_mem

private theorem generateMonotoneClass_compl (h𝒜 : IsSetAlgebra 𝒜)
    (hs : s ∈ generateMonotoneClass 𝒜) : sᶜ ∈ generateMonotoneClass 𝒜 := by
  induction hs with
  | basic s hs => exact .basic _ (h𝒜.compl_mem hs)
  | iUnion s h_mono _ ih =>
      rw [compl_iUnion]
      exact .iInter _ (fun _ _ h ↦ compl_subset_compl.mpr (h_mono h)) ih
  | iInter s h_anti _ ih =>
      rw [compl_iInter]
      exact .iUnion _ (fun _ _ h ↦ compl_subset_compl.mpr (h_anti h)) ih

private theorem mem_generateMonotoneClass_inter_left (h𝒜 : IsSetAlgebra 𝒜) (hs : s ∈ 𝒜)
    (ht : t ∈ generateMonotoneClass 𝒜) : s ∩ t ∈ generateMonotoneClass 𝒜 := by
  induction ht with
  | basic t ht => exact .basic _ (h𝒜.inter_mem hs ht)
  | iUnion t h_mono _ ih =>
      rw [inter_iUnion]
      exact .iUnion _ (fun _ _ h ↦ inter_subset_inter_right _ (h_mono h)) ih
  | iInter t h_anti _ ih =>
      rw [inter_iInter]
      exact .iInter _ (fun _ _ h ↦ inter_subset_inter_right _ (h_anti h)) ih

private theorem mem_generateMonotoneClass_inter (h𝒜 : IsSetAlgebra 𝒜)
    (hs : s ∈ generateMonotoneClass 𝒜) (ht : t ∈ generateMonotoneClass 𝒜) :
    s ∩ t ∈ generateMonotoneClass 𝒜 := by
  induction hs with
  | basic s hs => exact mem_generateMonotoneClass_inter_left h𝒜 hs ht
  | iUnion s h_mono _ ih =>
      rw [iUnion_inter]
      exact .iUnion _ (fun _ _ h ↦ inter_subset_inter_left _ (h_mono h)) ih
  | iInter s h_anti _ ih =>
      rw [iInter_inter]
      exact .iInter _ (fun _ _ h ↦ inter_subset_inter_left _ (h_anti h)) ih

/-- The monotone class generated by an algebra of sets is itself an algebra of sets. -/
theorem isSetAlgebra_generateMonotoneClass (h𝒜 : IsSetAlgebra 𝒜) :
    IsSetAlgebra (generateMonotoneClass 𝒜) where
  empty_mem := .basic _ h𝒜.empty_mem
  compl_mem := by
    intro s hs
    exact generateMonotoneClass_compl h𝒜 hs
  union_mem := by
    intro s t hs ht
    simpa only [compl_inter, compl_compl] using
      generateMonotoneClass_compl h𝒜
        (mem_generateMonotoneClass_inter h𝒜
          (generateMonotoneClass_compl h𝒜 hs) (generateMonotoneClass_compl h𝒜 ht))

/-- **Monotone class theorem**: the monotone class generated by an algebra of sets is exactly the
σ-algebra generated by that algebra. -/
theorem generateMonotoneClass_eq_generateFrom (h𝒜 : IsSetAlgebra 𝒜) :
    generateMonotoneClass 𝒜 = generateFrom 𝒜 := by
  apply Set.Subset.antisymm
  · exact (SigmaAlgebra.isMonotoneClass _).generateMonotoneClass_subset
      (fun _ hs ↦ mem_generateFrom hs)
  · let m : SigmaAlgebra α :=
      { carrier := generateMonotoneClass 𝒜
        isSigmaAlgebra :=
          { empty_mem := (isSetAlgebra_generateMonotoneClass h𝒜).empty_mem
            compl_mem := (isSetAlgebra_generateMonotoneClass h𝒜).compl_mem
            iUnion_mem_nat := fun _ hs ↦
              (isSetAlgebra_generateMonotoneClass h𝒜).iUnion_mem_of_isMonotoneClass
                isMonotoneClass_generateMonotoneClass hs } }
    exact generateFrom_le (m := m) fun _ hs ↦ self_subset_generateMonotoneClass hs

end MeasureTheory

namespace SigmaAlgebra

open MeasureTheory

variable {α : Type*} {𝒜 : Set (Set α)}

/-- Monotone-class induction for sets measurable with respect to the σ-algebra generated by an
algebra of sets. -/
@[elab_as_elim]
theorem induction_on_monotoneClass {m : SigmaAlgebra α}
    {C : ∀ s : Set α, s ∈ m → Prop}
    (h_eq : m = generateFrom 𝒜) (h𝒜 : IsSetAlgebra 𝒜)
    (basic : ∀ s (hs : s ∈ 𝒜), C s (h_eq ▸ mem_generateFrom hs))
    (iUnion : ∀ (s : ℕ → Set α) (_h_mono : Monotone s)
      (hs : ∀ n, s n ∈ m), (∀ n, C (s n) (hs n)) → C (⋃ n, s n) (m.iUnion_mem hs))
    (iInter : ∀ (s : ℕ → Set α) (_h_anti : Antitone s)
      (hs : ∀ n, s n ∈ m), (∀ n, C (s n) (hs n)) → C (⋂ n, s n) (m.iInter_mem hs))
    {s : Set α} (hs : s ∈ m) : C s hs := by
  have eq (t : Set α) : t ∈ m ↔ t ∈ generateMonotoneClass 𝒜 := by
    rw [h_eq]
    change t ∈ (generateFrom 𝒜 : Set (Set α)) ↔ t ∈ generateMonotoneClass 𝒜
    rw [generateMonotoneClass_eq_generateFrom h𝒜]
  have hs' : s ∈ generateMonotoneClass 𝒜 := (eq s).mp hs
  change MeasureTheory.GenerateMonotoneClass 𝒜 s at hs'
  simpa only using MeasureTheory.GenerateMonotoneClass.rec
    (motive := fun s hs ↦ C s ((eq s).mpr hs))
    (fun s hs ↦ by simpa only using basic s hs)
    (fun s h_mono hs ih ↦ by
      simpa only using iUnion s h_mono (fun n ↦ (eq (s n)).mpr (hs n)) fun n ↦ by
        simpa only using ih n)
    (fun s h_anti hs ih ↦ by
      simpa only using iInter s h_anti (fun n ↦ (eq (s n)).mpr (hs n)) fun n ↦ by
        simpa only using ih n) hs'

end SigmaAlgebra
