/-
Copyright (c) 2020 Floris van Doorn. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Floris van Doorn
-/
module

public import Mathlib.MeasureTheory.SigmaAlgebra.Embedding
public import Mathlib.MeasureTheory.PiSystem

/-!
# The product sigma algebra

This file talks about the measurability of operations on binary functions.
-/

public section

assert_not_exists MeasureTheory.Measure

noncomputable section

open Set SigmaAlgebra

variable {α β : Type*} [SigmaAlgebra α] [SigmaAlgebra β]

/-- The product of generated σ-algebras is the one generated by rectangles, if both generating sets
  are countably spanning. -/
theorem generateFrom_prod_eq {α β} {C : Set (Set α)} {D : Set (Set β)} (hC : IsCountablySpanning C)
    (hD : IsCountablySpanning D) :
    @Prod.instSigmaAlgebra _ _ (generateFrom C) (generateFrom D) =
      generateFrom (image2 (· ×ˢ ·) C D) := by
  apply le_antisymm
  · refine sup_le ?_ ?_ <;> rw [comap_generateFrom] <;> apply generateFrom_le <;>
      rintro _ ⟨s, hs, rfl⟩
    · rcases hD with ⟨t, h1t, h2t⟩
      rw [← prod_univ, ← h2t, prod_iUnion]
      apply MeasurableSet.iUnion
      intro n
      exact GenerateMeasurable.basic _ ⟨s, hs, t n, h1t n, rfl⟩
    · rcases hC with ⟨t, h1t, h2t⟩
      rw [← univ_prod, ← h2t, iUnion_prod_const]
      apply MeasurableSet.iUnion
      rintro n
      exact GenerateMeasurable.basic _ (mem_image2_of_mem (h1t n) hs)
  · apply generateFrom_le
    rintro _ ⟨s, hs, t, ht, rfl⟩
    dsimp only
    rw [prod_eq]
    apply (@Prod.instSigmaAlgebra α β (generateFrom C) (generateFrom D)).inter_mem
    · exact measurable_fst (GenerateMeasurable.basic _ hs)
    · exact measurable_snd (GenerateMeasurable.basic _ ht)

/-- If `C` and `D` generate the σ-algebras on `α` resp. `β`, then rectangles formed by `C` and `D`
  generate the σ-algebra on `α × β`. -/
theorem generateFrom_eq_prod {C : Set (Set α)} {D : Set (Set β)} (hC : generateFrom C = ‹_›)
    (hD : generateFrom D = ‹_›) (h2C : IsCountablySpanning C) (h2D : IsCountablySpanning D) :
    generateFrom (image2 (· ×ˢ ·) C D) = Prod.instSigmaAlgebra := by
  rw [← hC, ← hD, generateFrom_prod_eq h2C h2D]

/-- The product σ-algebra is generated from boxes, i.e. `s ×ˢ t` for sets `s : Set α` and
  `t : Set β`. -/
lemma generateFrom_prod :
    generateFrom (image2 (· ×ˢ ·) ((inferInstance : SigmaAlgebra α) : Set (Set α))
      ((inferInstance : SigmaAlgebra β) : Set (Set β))) =
      Prod.instSigmaAlgebra :=
  generateFrom_eq_prod
    (le_antisymm (generateFrom_le fun _ hs ↦ hs) fun _ hs ↦ GenerateMeasurable.basic _ hs)
    (le_antisymm (generateFrom_le fun _ hs ↦ hs) fun _ hs ↦ GenerateMeasurable.basic _ hs)
    ⟨fun _ ↦ univ, fun _ ↦ (inferInstance : SigmaAlgebra α).univ_mem, iUnion_const _⟩
    ⟨fun _ ↦ univ, fun _ ↦ (inferInstance : SigmaAlgebra β).univ_mem, iUnion_const _⟩

/-- Rectangles form a π-system. -/
lemma isPiSystem_prod :
    IsPiSystem (image2 (· ×ˢ ·) ((inferInstance : SigmaAlgebra α) : Set (Set α))
      ((inferInstance : SigmaAlgebra β) : Set (Set β))) :=
  (inferInstance : SigmaAlgebra α).isPiSystem.prod
    (inferInstance : SigmaAlgebra β).isPiSystem

/-- The comap of a product is the supremum of the comaps. -/
lemma SigmaAlgebra.comap_prodMk {α β γ : Type*} {mβ : SigmaAlgebra β} {mγ : SigmaAlgebra γ}
    (X : α → β) (Y : α → γ) :
    (mβ.prod mγ).comap (fun ω ↦ (X ω, Y ω)) = mβ.comap X ⊔ mγ.comap Y := by
  simp_rw [SigmaAlgebra.prod, comap_sup, comap_comp]
  rfl

/-- The comap of `Prod.map` is the product of the comaps. -/
lemma SigmaAlgebra.comap_prodMap {α β γ δ : Type*}
    {mα : SigmaAlgebra α} {mβ : SigmaAlgebra β} (X : γ → α) (Y : δ → β) :
    (mα.prod mβ).comap (Prod.map X Y) = (mα.comap X).prod (mβ.comap Y) := by
  simp_rw [SigmaAlgebra.prod, comap_sup, comap_comp]
  rfl

/-- `Prod.map` of two measurable embeddings is a measurable embedding. -/
lemma MeasurableEmbedding.prodMap {α β γ δ : Type*} {mα : SigmaAlgebra α}
    {mβ : SigmaAlgebra β} {mγ : SigmaAlgebra γ} {mδ : SigmaAlgebra δ} {f : α → β}
    {g : γ → δ} (hg : MeasurableEmbedding g) (hf : MeasurableEmbedding f) :
    MeasurableEmbedding (Prod.map g f) := by
  rw [MeasurableEmbedding.iff_comap_eq]
  refine ⟨hg.injective.prodMap hf.injective, ?_, ?_⟩
  · rw [Prod.instSigmaAlgebra, Prod.instSigmaAlgebra, SigmaAlgebra.comap_prodMap,
      hg.comap_eq, hf.comap_eq]
  · rw [range_prodMap]
    exact hg.measurableSet_range.prod hf.measurableSet_range

lemma MeasurableEmbedding.prodMk_left {β γ : Type*} [MeasurableSingletonClass α]
    {mβ : SigmaAlgebra β} {mγ : SigmaAlgebra γ}
    (x : α) {f : γ → β} (hf : MeasurableEmbedding f) :
    MeasurableEmbedding (fun y ↦ (x, f y)) where
  injective := by
    intro y y'
    simp only [Prod.mk.injEq, true_and]
    exact fun h ↦ hf.injective h
  measurable := Measurable.prodMk measurable_const hf.measurable
  measurableSet_image' := by
    intro s hs
    convert! (MeasurableSet.singleton x).prod (hf.measurableSet_image.mpr hs)
    ext x
    simp [Prod.ext_iff, eq_comm, ← exists_and_left, and_left_comm]

lemma measurableEmbedding_prodMk_left [MeasurableSingletonClass α] (x : α) :
    MeasurableEmbedding (Prod.mk x : β → α × β) :=
  MeasurableEmbedding.prodMk_left x MeasurableEmbedding.id

lemma MeasurableEmbedding.prodMk_right {β γ : Type*} [MeasurableSingletonClass α]
    {mβ : SigmaAlgebra β} {mγ : SigmaAlgebra γ}
    {f : γ → β} (hf : MeasurableEmbedding f) (x : α) :
    MeasurableEmbedding (fun y ↦ (f y, x)) :=
  MeasurableEquiv.prodComm.measurableEmbedding.comp (hf.prodMk_left _)

lemma measurableEmbedding_prod_mk_right [MeasurableSingletonClass α] (x : α) :
    MeasurableEmbedding (fun y ↦ (y, x) : β → β × α) :=
  MeasurableEmbedding.prodMk_right MeasurableEmbedding.id x
